server.port=4000
spring.application.name=chainsight-api
spring.datasource.url=jdbc:postgresql://localhost:5432/msme_supplychain
spring.datasource.username=postgres
spring.datasource.password=Srini@1956

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver

# --- ChainSight Configuration ---

